<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Squad小帮手</AssemblyName>
    <RootNamespace>SquadTools</RootNamespace>
    <ApplicationIcon>ico\squadtools.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Title>Squad小帮手</Title>
    <Product>Squad小帮手</Product>
    <Description>Squad小帮手</Description>
    <Company>lyl-103</Company>
    <Authors>lyl-103</Authors>
    <Version>1.4.2</Version>
    <AssemblyVersion>1.4.2.0</AssemblyVersion>
    <FileVersion>1.4.2.0</FileVersion>
    <InformationalVersion>1.4.2</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2903.40" />
  </ItemGroup>
  <Target Name="CopyLocalMapHost" AfterTargets="Publish">
    <ItemGroup>
      <LocalMapHostFiles Include="I:\opencode02\Squad.ICU\MapHost\**\*" />
    </ItemGroup>
    <Copy SourceFiles="@(LocalMapHostFiles)" DestinationFiles="@(LocalMapHostFiles->'$(PublishDir)MapHost\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>
</Project>
