<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Squad小帮手</AssemblyName>
    <RootNamespace>SquadTools</RootNamespace>
    <ApplicationIcon>ico\squadtools.ico</ApplicationIcon>
    <Title>Squad小帮手</Title>
    <Product>Squad小帮手</Product>
    <Description>Squad小帮手</Description>
    <Company>lyl-103</Company>
    <Authors>lyl-103</Authors>
    <Version>1.4.0</Version>
    <AssemblyVersion>1.4.0.0</AssemblyVersion>
    <FileVersion>1.4.0.0</FileVersion>
    <InformationalVersion>1.4.0</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
</Project>
